// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package space.whm.open;

public final class CommonDemo {
  private CommonDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *年级枚举类
   * </pre>
   *
   * Protobuf enum {@code Grade}
   */
  public enum Grade
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULTG = 0;</code>
     */
    DEFAULTG(0),
    /**
     * <code>GRADE1 = 1;</code>
     */
    GRADE1(1),
    /**
     * <code>GRADE2 = 2;</code>
     */
    GRADE2(2),
    /**
     * <code>GRADE3 = 3;</code>
     */
    GRADE3(3),
    /**
     * <code>GRADE4 = 4;</code>
     */
    GRADE4(4),
    /**
     * <code>GRADE5 = 5;</code>
     */
    GRADE5(5),
    /**
     * <code>GRADE6 = 6;</code>
     */
    GRADE6(6),
    /**
     * <code>GRADE7 = 7;</code>
     */
    GRADE7(7),
    /**
     * <code>GRADE8 = 8;</code>
     */
    GRADE8(8),
    /**
     * <code>GRADE9 = 9;</code>
     */
    GRADE9(9),
    /**
     * <code>GRADE10 = 10;</code>
     */
    GRADE10(10),
    /**
     * <code>GRADE11 = 11;</code>
     */
    GRADE11(11),
    /**
     * <code>GRADE12 = 12;</code>
     */
    GRADE12(12),
    /**
     * <code>GRADE654 = 654;</code>
     */
    GRADE654(654),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULTG = 0;</code>
     */
    public static final int DEFAULTG_VALUE = 0;
    /**
     * <code>GRADE1 = 1;</code>
     */
    public static final int GRADE1_VALUE = 1;
    /**
     * <code>GRADE2 = 2;</code>
     */
    public static final int GRADE2_VALUE = 2;
    /**
     * <code>GRADE3 = 3;</code>
     */
    public static final int GRADE3_VALUE = 3;
    /**
     * <code>GRADE4 = 4;</code>
     */
    public static final int GRADE4_VALUE = 4;
    /**
     * <code>GRADE5 = 5;</code>
     */
    public static final int GRADE5_VALUE = 5;
    /**
     * <code>GRADE6 = 6;</code>
     */
    public static final int GRADE6_VALUE = 6;
    /**
     * <code>GRADE7 = 7;</code>
     */
    public static final int GRADE7_VALUE = 7;
    /**
     * <code>GRADE8 = 8;</code>
     */
    public static final int GRADE8_VALUE = 8;
    /**
     * <code>GRADE9 = 9;</code>
     */
    public static final int GRADE9_VALUE = 9;
    /**
     * <code>GRADE10 = 10;</code>
     */
    public static final int GRADE10_VALUE = 10;
    /**
     * <code>GRADE11 = 11;</code>
     */
    public static final int GRADE11_VALUE = 11;
    /**
     * <code>GRADE12 = 12;</code>
     */
    public static final int GRADE12_VALUE = 12;
    /**
     * <code>GRADE654 = 654;</code>
     */
    public static final int GRADE654_VALUE = 654;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Grade valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Grade forNumber(int value) {
      switch (value) {
        case 0: return DEFAULTG;
        case 1: return GRADE1;
        case 2: return GRADE2;
        case 3: return GRADE3;
        case 4: return GRADE4;
        case 5: return GRADE5;
        case 6: return GRADE6;
        case 7: return GRADE7;
        case 8: return GRADE8;
        case 9: return GRADE9;
        case 10: return GRADE10;
        case 11: return GRADE11;
        case 12: return GRADE12;
        case 654: return GRADE654;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Grade>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Grade> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Grade>() {
            public Grade findValueByNumber(int number) {
              return Grade.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(0);
    }

    private static final Grade[] VALUES = values();

    public static Grade valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Grade(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Grade)
  }

  /**
   * <pre>
   *学科枚举类
   * </pre>
   *
   * Protobuf enum {@code Knowledge}
   */
  public enum Knowledge
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULTK = 0;</code>
     */
    DEFAULTK(0),
    /**
     * <code>YUWEN = 1;</code>
     */
    YUWEN(1),
    /**
     * <code>SHUXUE = 2;</code>
     */
    SHUXUE(2),
    /**
     * <code>YINGYU = 3;</code>
     */
    YINGYU(3),
    /**
     * <code>WULI = 4;</code>
     */
    WULI(4),
    /**
     * <code>HUAXUE = 5;</code>
     */
    HUAXUE(5),
    /**
     * <code>KEXUE = 6;</code>
     */
    KEXUE(6),
    /**
     * <code>DAODEYUFAZHI = 7;</code>
     */
    DAODEYUFAZHI(7),
    /**
     * <code>LISHI = 8;</code>
     */
    LISHI(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULTK = 0;</code>
     */
    public static final int DEFAULTK_VALUE = 0;
    /**
     * <code>YUWEN = 1;</code>
     */
    public static final int YUWEN_VALUE = 1;
    /**
     * <code>SHUXUE = 2;</code>
     */
    public static final int SHUXUE_VALUE = 2;
    /**
     * <code>YINGYU = 3;</code>
     */
    public static final int YINGYU_VALUE = 3;
    /**
     * <code>WULI = 4;</code>
     */
    public static final int WULI_VALUE = 4;
    /**
     * <code>HUAXUE = 5;</code>
     */
    public static final int HUAXUE_VALUE = 5;
    /**
     * <code>KEXUE = 6;</code>
     */
    public static final int KEXUE_VALUE = 6;
    /**
     * <code>DAODEYUFAZHI = 7;</code>
     */
    public static final int DAODEYUFAZHI_VALUE = 7;
    /**
     * <code>LISHI = 8;</code>
     */
    public static final int LISHI_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Knowledge valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Knowledge forNumber(int value) {
      switch (value) {
        case 0: return DEFAULTK;
        case 1: return YUWEN;
        case 2: return SHUXUE;
        case 3: return YINGYU;
        case 4: return WULI;
        case 5: return HUAXUE;
        case 6: return KEXUE;
        case 7: return DAODEYUFAZHI;
        case 8: return LISHI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Knowledge>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Knowledge> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Knowledge>() {
            public Knowledge findValueByNumber(int number) {
              return Knowledge.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(1);
    }

    private static final Knowledge[] VALUES = values();

    public static Knowledge valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Knowledge(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Knowledge)
  }

  /**
   * <pre>
   *课程状态 0删除 1上线状态 2 下线状态
   * </pre>
   *
   * Protobuf enum {@code IsAvaliable}
   */
  public enum IsAvaliable
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULTI = 0;</code>
     */
    DEFAULTI(0),
    /**
     * <code>ONLINE = 1;</code>
     */
    ONLINE(1),
    /**
     * <code>OFFLINE = 2;</code>
     */
    OFFLINE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULTI = 0;</code>
     */
    public static final int DEFAULTI_VALUE = 0;
    /**
     * <code>ONLINE = 1;</code>
     */
    public static final int ONLINE_VALUE = 1;
    /**
     * <code>OFFLINE = 2;</code>
     */
    public static final int OFFLINE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static IsAvaliable valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static IsAvaliable forNumber(int value) {
      switch (value) {
        case 0: return DEFAULTI;
        case 1: return ONLINE;
        case 2: return OFFLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IsAvaliable>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        IsAvaliable> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IsAvaliable>() {
            public IsAvaliable findValueByNumber(int number) {
              return IsAvaliable.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(2);
    }

    private static final IsAvaliable[] VALUES = values();

    public static IsAvaliable valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private IsAvaliable(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IsAvaliable)
  }

  /**
   * <pre>
   *是否免费 0免费 1不免费
   * </pre>
   *
   * Protobuf enum {@code IsFree}
   */
  public enum IsFree
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Y = 0;</code>
     */
    Y(0),
    /**
     * <code>N = 1;</code>
     */
    N(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Y = 0;</code>
     */
    public static final int Y_VALUE = 0;
    /**
     * <code>N = 1;</code>
     */
    public static final int N_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static IsFree valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static IsFree forNumber(int value) {
      switch (value) {
        case 0: return Y;
        case 1: return N;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IsFree>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        IsFree> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IsFree>() {
            public IsFree findValueByNumber(int number) {
              return IsFree.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(3);
    }

    private static final IsFree[] VALUES = values();

    public static IsFree valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private IsFree(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IsFree)
  }

  /**
   * <pre>
   *学段 1小学 2初中 3高中
   * </pre>
   *
   * Protobuf enum {@code LearnStage}
   */
  public enum LearnStage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULTL = 0;</code>
     */
    DEFAULTL(0),
    /**
     * <code>XIAOXUE = 1;</code>
     */
    XIAOXUE(1),
    /**
     * <code>CHUZHONG = 2;</code>
     */
    CHUZHONG(2),
    /**
     * <code>GAOZHONG = 3;</code>
     */
    GAOZHONG(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULTL = 0;</code>
     */
    public static final int DEFAULTL_VALUE = 0;
    /**
     * <code>XIAOXUE = 1;</code>
     */
    public static final int XIAOXUE_VALUE = 1;
    /**
     * <code>CHUZHONG = 2;</code>
     */
    public static final int CHUZHONG_VALUE = 2;
    /**
     * <code>GAOZHONG = 3;</code>
     */
    public static final int GAOZHONG_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static LearnStage valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LearnStage forNumber(int value) {
      switch (value) {
        case 0: return DEFAULTL;
        case 1: return XIAOXUE;
        case 2: return CHUZHONG;
        case 3: return GAOZHONG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LearnStage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LearnStage> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LearnStage>() {
            public LearnStage findValueByNumber(int number) {
              return LearnStage.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(4);
    }

    private static final LearnStage[] VALUES = values();

    public static LearnStage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LearnStage(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LearnStage)
  }

  /**
   * Protobuf enum {@code Sex}
   */
  public enum Sex
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *女
     * </pre>
     *
     * <code>WOMAN = 0;</code>
     */
    WOMAN(0),
    /**
     * <pre>
     *男
     * </pre>
     *
     * <code>MAN = 1;</code>
     */
    MAN(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *女
     * </pre>
     *
     * <code>WOMAN = 0;</code>
     */
    public static final int WOMAN_VALUE = 0;
    /**
     * <pre>
     *男
     * </pre>
     *
     * <code>MAN = 1;</code>
     */
    public static final int MAN_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Sex valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Sex forNumber(int value) {
      switch (value) {
        case 0: return WOMAN;
        case 1: return MAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sex> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
            public Sex findValueByNumber(int number) {
              return Sex.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonDemo.getDescriptor().getEnumTypes().get(5);
    }

    private static final Sex[] VALUES = values();

    public static Sex valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sex(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Sex)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Common.proto*\267\001\n\005Grade\022\014\n\010DEFAULTG\020\000\022\n" +
      "\n\006GRADE1\020\001\022\n\n\006GRADE2\020\002\022\n\n\006GRADE3\020\003\022\n\n\006GR" +
      "ADE4\020\004\022\n\n\006GRADE5\020\005\022\n\n\006GRADE6\020\006\022\n\n\006GRADE7" +
      "\020\007\022\n\n\006GRADE8\020\010\022\n\n\006GRADE9\020\t\022\013\n\007GRADE10\020\n\022" +
      "\013\n\007GRADE11\020\013\022\013\n\007GRADE12\020\014\022\r\n\010GRADE654\020\216\005" +
      "*z\n\tKnowledge\022\014\n\010DEFAULTK\020\000\022\t\n\005YUWEN\020\001\022\n" +
      "\n\006SHUXUE\020\002\022\n\n\006YINGYU\020\003\022\010\n\004WULI\020\004\022\n\n\006HUAX" +
      "UE\020\005\022\t\n\005KEXUE\020\006\022\020\n\014DAODEYUFAZHI\020\007\022\t\n\005LIS" +
      "HI\020\010*4\n\013IsAvaliable\022\014\n\010DEFAULTI\020\000\022\n\n\006ONL" +
      "INE\020\001\022\013\n\007OFFLINE\020\002*\026\n\006IsFree\022\005\n\001Y\020\000\022\005\n\001N" +
      "\020\001*C\n\nLearnStage\022\014\n\010DEFAULTL\020\000\022\013\n\007XIAOXU" +
      "E\020\001\022\014\n\010CHUZHONG\020\002\022\014\n\010GAOZHONG\020\003*\031\n\003Sex\022\t" +
      "\n\005WOMAN\020\000\022\007\n\003MAN\020\001B\034\n\016space.whm.openB\nCo" +
      "mmonDemob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
