// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportPosBill.proto

package space.whm.open;

public final class ReportPosBillInfo {
  private ReportPosBillInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReportPosBillOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReportPosBill)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 门店ID
     * </pre>
     *
     * <code>int32 ognid = 1;</code>
     * @return The ognid.
     */
    int getOgnid();

    /**
     * <pre>
     * 账单ID
     * </pre>
     *
     * <code>string billid = 2;</code>
     * @return The billid.
     */
    String getBillid();
    /**
     * <pre>
     * 账单ID
     * </pre>
     *
     * <code>string billid = 2;</code>
     * @return The bytes for billid.
     */
    com.google.protobuf.ByteString
        getBillidBytes();

    /**
     * <pre>
     * 账单号
     * </pre>
     *
     * <code>string billno = 3;</code>
     * @return The billno.
     */
    String getBillno();
    /**
     * <pre>
     * 账单号
     * </pre>
     *
     * <code>string billno = 3;</code>
     * @return The bytes for billno.
     */
    com.google.protobuf.ByteString
        getBillnoBytes();

    /**
     * <pre>
     *	业务类型
     * </pre>
     *
     * <code>int32 businesstype = 4;</code>
     * @return The businesstype.
     */
    int getBusinesstype();

    /**
     * <pre>
     * 订单来源
     * </pre>
     *
     * <code>int32 source = 5;</code>
     * @return The source.
     */
    int getSource();

    /**
     * <pre>
     * 桌号/取餐号
     * </pre>
     *
     * <code>string tableno = 6;</code>
     * @return The tableno.
     */
    String getTableno();
    /**
     * <pre>
     * 桌号/取餐号
     * </pre>
     *
     * <code>string tableno = 6;</code>
     * @return The bytes for tableno.
     */
    com.google.protobuf.ByteString
        getTablenoBytes();

    /**
     * <pre>
     * 消费合计
     * </pre>
     *
     * <code>double totalconsume = 7;</code>
     * @return The totalconsume.
     */
    double getTotalconsume();

    /**
     * <pre>
     * 收款合计
     * </pre>
     *
     * <code>double realprice = 8;</code>
     * @return The realprice.
     */
    double getRealprice();

    /**
     * <pre>
     * 支付方式名称，多个逗号分割
     * </pre>
     *
     * <code>string pmname = 9;</code>
     * @return The pmname.
     */
    String getPmname();
    /**
     * <pre>
     * 支付方式名称，多个逗号分割
     * </pre>
     *
     * <code>string pmname = 9;</code>
     * @return The bytes for pmname.
     */
    com.google.protobuf.ByteString
        getPmnameBytes();

    /**
     * <pre>
     * 结账时间
     * </pre>
     *
     * <code>string paytime = 10;</code>
     * @return The paytime.
     */
    String getPaytime();
    /**
     * <pre>
     * 结账时间
     * </pre>
     *
     * <code>string paytime = 10;</code>
     * @return The bytes for paytime.
     */
    com.google.protobuf.ByteString
        getPaytimeBytes();

    /**
     * <pre>
     * 订单状态：1.有效 2.无效 3 未结
     * </pre>
     *
     * <code>int32 billstatus = 11;</code>
     * @return The billstatus.
     */
    int getBillstatus();
  }
  /**
   * Protobuf type {@code ReportPosBill}
   */
  public  static final class ReportPosBill extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReportPosBill)
      ReportPosBillOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportPosBill.newBuilder() to construct.
    private ReportPosBill(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportPosBill() {
      billid_ = "";
      billno_ = "";
      tableno_ = "";
      pmname_ = "";
      paytime_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReportPosBill();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportPosBill(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ognid_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              billid_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              billno_ = s;
              break;
            }
            case 32: {

              businesstype_ = input.readInt32();
              break;
            }
            case 40: {

              source_ = input.readInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              tableno_ = s;
              break;
            }
            case 57: {

              totalconsume_ = input.readDouble();
              break;
            }
            case 65: {

              realprice_ = input.readDouble();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              pmname_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              paytime_ = s;
              break;
            }
            case 88: {

              billstatus_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReportPosBillInfo.internal_static_ReportPosBill_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReportPosBillInfo.internal_static_ReportPosBill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReportPosBill.class, Builder.class);
    }

    public static final int OGNID_FIELD_NUMBER = 1;
    private int ognid_;
    /**
     * <pre>
     * 门店ID
     * </pre>
     *
     * <code>int32 ognid = 1;</code>
     * @return The ognid.
     */
    public int getOgnid() {
      return ognid_;
    }

    public static final int BILLID_FIELD_NUMBER = 2;
    private volatile Object billid_;
    /**
     * <pre>
     * 账单ID
     * </pre>
     *
     * <code>string billid = 2;</code>
     * @return The billid.
     */
    public String getBillid() {
      Object ref = billid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        billid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 账单ID
     * </pre>
     *
     * <code>string billid = 2;</code>
     * @return The bytes for billid.
     */
    public com.google.protobuf.ByteString
        getBillidBytes() {
      Object ref = billid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        billid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BILLNO_FIELD_NUMBER = 3;
    private volatile Object billno_;
    /**
     * <pre>
     * 账单号
     * </pre>
     *
     * <code>string billno = 3;</code>
     * @return The billno.
     */
    public String getBillno() {
      Object ref = billno_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        billno_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 账单号
     * </pre>
     *
     * <code>string billno = 3;</code>
     * @return The bytes for billno.
     */
    public com.google.protobuf.ByteString
        getBillnoBytes() {
      Object ref = billno_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        billno_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUSINESSTYPE_FIELD_NUMBER = 4;
    private int businesstype_;
    /**
     * <pre>
     *	业务类型
     * </pre>
     *
     * <code>int32 businesstype = 4;</code>
     * @return The businesstype.
     */
    public int getBusinesstype() {
      return businesstype_;
    }

    public static final int SOURCE_FIELD_NUMBER = 5;
    private int source_;
    /**
     * <pre>
     * 订单来源
     * </pre>
     *
     * <code>int32 source = 5;</code>
     * @return The source.
     */
    public int getSource() {
      return source_;
    }

    public static final int TABLENO_FIELD_NUMBER = 6;
    private volatile Object tableno_;
    /**
     * <pre>
     * 桌号/取餐号
     * </pre>
     *
     * <code>string tableno = 6;</code>
     * @return The tableno.
     */
    public String getTableno() {
      Object ref = tableno_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tableno_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 桌号/取餐号
     * </pre>
     *
     * <code>string tableno = 6;</code>
     * @return The bytes for tableno.
     */
    public com.google.protobuf.ByteString
        getTablenoBytes() {
      Object ref = tableno_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tableno_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALCONSUME_FIELD_NUMBER = 7;
    private double totalconsume_;
    /**
     * <pre>
     * 消费合计
     * </pre>
     *
     * <code>double totalconsume = 7;</code>
     * @return The totalconsume.
     */
    public double getTotalconsume() {
      return totalconsume_;
    }

    public static final int REALPRICE_FIELD_NUMBER = 8;
    private double realprice_;
    /**
     * <pre>
     * 收款合计
     * </pre>
     *
     * <code>double realprice = 8;</code>
     * @return The realprice.
     */
    public double getRealprice() {
      return realprice_;
    }

    public static final int PMNAME_FIELD_NUMBER = 9;
    private volatile Object pmname_;
    /**
     * <pre>
     * 支付方式名称，多个逗号分割
     * </pre>
     *
     * <code>string pmname = 9;</code>
     * @return The pmname.
     */
    public String getPmname() {
      Object ref = pmname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pmname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 支付方式名称，多个逗号分割
     * </pre>
     *
     * <code>string pmname = 9;</code>
     * @return The bytes for pmname.
     */
    public com.google.protobuf.ByteString
        getPmnameBytes() {
      Object ref = pmname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pmname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYTIME_FIELD_NUMBER = 10;
    private volatile Object paytime_;
    /**
     * <pre>
     * 结账时间
     * </pre>
     *
     * <code>string paytime = 10;</code>
     * @return The paytime.
     */
    public String getPaytime() {
      Object ref = paytime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paytime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 结账时间
     * </pre>
     *
     * <code>string paytime = 10;</code>
     * @return The bytes for paytime.
     */
    public com.google.protobuf.ByteString
        getPaytimeBytes() {
      Object ref = paytime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paytime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BILLSTATUS_FIELD_NUMBER = 11;
    private int billstatus_;
    /**
     * <pre>
     * 订单状态：1.有效 2.无效 3 未结
     * </pre>
     *
     * <code>int32 billstatus = 11;</code>
     * @return The billstatus.
     */
    public int getBillstatus() {
      return billstatus_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ognid_ != 0) {
        output.writeInt32(1, ognid_);
      }
      if (!getBillidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, billid_);
      }
      if (!getBillnoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, billno_);
      }
      if (businesstype_ != 0) {
        output.writeInt32(4, businesstype_);
      }
      if (source_ != 0) {
        output.writeInt32(5, source_);
      }
      if (!getTablenoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tableno_);
      }
      if (totalconsume_ != 0D) {
        output.writeDouble(7, totalconsume_);
      }
      if (realprice_ != 0D) {
        output.writeDouble(8, realprice_);
      }
      if (!getPmnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, pmname_);
      }
      if (!getPaytimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, paytime_);
      }
      if (billstatus_ != 0) {
        output.writeInt32(11, billstatus_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ognid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ognid_);
      }
      if (!getBillidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, billid_);
      }
      if (!getBillnoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, billno_);
      }
      if (businesstype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, businesstype_);
      }
      if (source_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, source_);
      }
      if (!getTablenoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tableno_);
      }
      if (totalconsume_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, totalconsume_);
      }
      if (realprice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, realprice_);
      }
      if (!getPmnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, pmname_);
      }
      if (!getPaytimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, paytime_);
      }
      if (billstatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, billstatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReportPosBill)) {
        return super.equals(obj);
      }
      ReportPosBill other = (ReportPosBill) obj;

      if (getOgnid()
          != other.getOgnid()) return false;
      if (!getBillid()
          .equals(other.getBillid())) return false;
      if (!getBillno()
          .equals(other.getBillno())) return false;
      if (getBusinesstype()
          != other.getBusinesstype()) return false;
      if (getSource()
          != other.getSource()) return false;
      if (!getTableno()
          .equals(other.getTableno())) return false;
      if (Double.doubleToLongBits(getTotalconsume())
          != Double.doubleToLongBits(
              other.getTotalconsume())) return false;
      if (Double.doubleToLongBits(getRealprice())
          != Double.doubleToLongBits(
              other.getRealprice())) return false;
      if (!getPmname()
          .equals(other.getPmname())) return false;
      if (!getPaytime()
          .equals(other.getPaytime())) return false;
      if (getBillstatus()
          != other.getBillstatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OGNID_FIELD_NUMBER;
      hash = (53 * hash) + getOgnid();
      hash = (37 * hash) + BILLID_FIELD_NUMBER;
      hash = (53 * hash) + getBillid().hashCode();
      hash = (37 * hash) + BILLNO_FIELD_NUMBER;
      hash = (53 * hash) + getBillno().hashCode();
      hash = (37 * hash) + BUSINESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBusinesstype();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource();
      hash = (37 * hash) + TABLENO_FIELD_NUMBER;
      hash = (53 * hash) + getTableno().hashCode();
      hash = (37 * hash) + TOTALCONSUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getTotalconsume()));
      hash = (37 * hash) + REALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRealprice()));
      hash = (37 * hash) + PMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPmname().hashCode();
      hash = (37 * hash) + PAYTIME_FIELD_NUMBER;
      hash = (53 * hash) + getPaytime().hashCode();
      hash = (37 * hash) + BILLSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getBillstatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReportPosBill parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportPosBill parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportPosBill parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportPosBill parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportPosBill parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportPosBill parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportPosBill parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportPosBill parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportPosBill parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReportPosBill parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportPosBill parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportPosBill parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReportPosBill prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportPosBill}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReportPosBill)
        ReportPosBillOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReportPosBillInfo.internal_static_ReportPosBill_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReportPosBillInfo.internal_static_ReportPosBill_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReportPosBill.class, Builder.class);
      }

      // Construct using space.whm.open.ReportPosBillInfo.ReportPosBill.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        ognid_ = 0;

        billid_ = "";

        billno_ = "";

        businesstype_ = 0;

        source_ = 0;

        tableno_ = "";

        totalconsume_ = 0D;

        realprice_ = 0D;

        pmname_ = "";

        paytime_ = "";

        billstatus_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReportPosBillInfo.internal_static_ReportPosBill_descriptor;
      }

      @Override
      public ReportPosBill getDefaultInstanceForType() {
        return ReportPosBill.getDefaultInstance();
      }

      @Override
      public ReportPosBill build() {
        ReportPosBill result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReportPosBill buildPartial() {
        ReportPosBill result = new ReportPosBill(this);
        result.ognid_ = ognid_;
        result.billid_ = billid_;
        result.billno_ = billno_;
        result.businesstype_ = businesstype_;
        result.source_ = source_;
        result.tableno_ = tableno_;
        result.totalconsume_ = totalconsume_;
        result.realprice_ = realprice_;
        result.pmname_ = pmname_;
        result.paytime_ = paytime_;
        result.billstatus_ = billstatus_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReportPosBill) {
          return mergeFrom((ReportPosBill)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReportPosBill other) {
        if (other == ReportPosBill.getDefaultInstance()) return this;
        if (other.getOgnid() != 0) {
          setOgnid(other.getOgnid());
        }
        if (!other.getBillid().isEmpty()) {
          billid_ = other.billid_;
          onChanged();
        }
        if (!other.getBillno().isEmpty()) {
          billno_ = other.billno_;
          onChanged();
        }
        if (other.getBusinesstype() != 0) {
          setBusinesstype(other.getBusinesstype());
        }
        if (other.getSource() != 0) {
          setSource(other.getSource());
        }
        if (!other.getTableno().isEmpty()) {
          tableno_ = other.tableno_;
          onChanged();
        }
        if (other.getTotalconsume() != 0D) {
          setTotalconsume(other.getTotalconsume());
        }
        if (other.getRealprice() != 0D) {
          setRealprice(other.getRealprice());
        }
        if (!other.getPmname().isEmpty()) {
          pmname_ = other.pmname_;
          onChanged();
        }
        if (!other.getPaytime().isEmpty()) {
          paytime_ = other.paytime_;
          onChanged();
        }
        if (other.getBillstatus() != 0) {
          setBillstatus(other.getBillstatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReportPosBill parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReportPosBill) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ognid_ ;
      /**
       * <pre>
       * 门店ID
       * </pre>
       *
       * <code>int32 ognid = 1;</code>
       * @return The ognid.
       */
      public int getOgnid() {
        return ognid_;
      }
      /**
       * <pre>
       * 门店ID
       * </pre>
       *
       * <code>int32 ognid = 1;</code>
       * @param value The ognid to set.
       * @return This builder for chaining.
       */
      public Builder setOgnid(int value) {
        
        ognid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 门店ID
       * </pre>
       *
       * <code>int32 ognid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOgnid() {
        
        ognid_ = 0;
        onChanged();
        return this;
      }

      private Object billid_ = "";
      /**
       * <pre>
       * 账单ID
       * </pre>
       *
       * <code>string billid = 2;</code>
       * @return The billid.
       */
      public String getBillid() {
        Object ref = billid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          billid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 账单ID
       * </pre>
       *
       * <code>string billid = 2;</code>
       * @return The bytes for billid.
       */
      public com.google.protobuf.ByteString
          getBillidBytes() {
        Object ref = billid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          billid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账单ID
       * </pre>
       *
       * <code>string billid = 2;</code>
       * @param value The billid to set.
       * @return This builder for chaining.
       */
      public Builder setBillid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        billid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账单ID
       * </pre>
       *
       * <code>string billid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBillid() {
        
        billid_ = getDefaultInstance().getBillid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账单ID
       * </pre>
       *
       * <code>string billid = 2;</code>
       * @param value The bytes for billid to set.
       * @return This builder for chaining.
       */
      public Builder setBillidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        billid_ = value;
        onChanged();
        return this;
      }

      private Object billno_ = "";
      /**
       * <pre>
       * 账单号
       * </pre>
       *
       * <code>string billno = 3;</code>
       * @return The billno.
       */
      public String getBillno() {
        Object ref = billno_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          billno_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 账单号
       * </pre>
       *
       * <code>string billno = 3;</code>
       * @return The bytes for billno.
       */
      public com.google.protobuf.ByteString
          getBillnoBytes() {
        Object ref = billno_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          billno_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账单号
       * </pre>
       *
       * <code>string billno = 3;</code>
       * @param value The billno to set.
       * @return This builder for chaining.
       */
      public Builder setBillno(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        billno_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账单号
       * </pre>
       *
       * <code>string billno = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBillno() {
        
        billno_ = getDefaultInstance().getBillno();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账单号
       * </pre>
       *
       * <code>string billno = 3;</code>
       * @param value The bytes for billno to set.
       * @return This builder for chaining.
       */
      public Builder setBillnoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        billno_ = value;
        onChanged();
        return this;
      }

      private int businesstype_ ;
      /**
       * <pre>
       *	业务类型
       * </pre>
       *
       * <code>int32 businesstype = 4;</code>
       * @return The businesstype.
       */
      public int getBusinesstype() {
        return businesstype_;
      }
      /**
       * <pre>
       *	业务类型
       * </pre>
       *
       * <code>int32 businesstype = 4;</code>
       * @param value The businesstype to set.
       * @return This builder for chaining.
       */
      public Builder setBusinesstype(int value) {
        
        businesstype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	业务类型
       * </pre>
       *
       * <code>int32 businesstype = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBusinesstype() {
        
        businesstype_ = 0;
        onChanged();
        return this;
      }

      private int source_ ;
      /**
       * <pre>
       * 订单来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       * @return The source.
       */
      public int getSource() {
        return source_;
      }
      /**
       * <pre>
       * 订单来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 订单来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private Object tableno_ = "";
      /**
       * <pre>
       * 桌号/取餐号
       * </pre>
       *
       * <code>string tableno = 6;</code>
       * @return The tableno.
       */
      public String getTableno() {
        Object ref = tableno_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tableno_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 桌号/取餐号
       * </pre>
       *
       * <code>string tableno = 6;</code>
       * @return The bytes for tableno.
       */
      public com.google.protobuf.ByteString
          getTablenoBytes() {
        Object ref = tableno_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tableno_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 桌号/取餐号
       * </pre>
       *
       * <code>string tableno = 6;</code>
       * @param value The tableno to set.
       * @return This builder for chaining.
       */
      public Builder setTableno(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableno_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 桌号/取餐号
       * </pre>
       *
       * <code>string tableno = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTableno() {
        
        tableno_ = getDefaultInstance().getTableno();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 桌号/取餐号
       * </pre>
       *
       * <code>string tableno = 6;</code>
       * @param value The bytes for tableno to set.
       * @return This builder for chaining.
       */
      public Builder setTablenoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableno_ = value;
        onChanged();
        return this;
      }

      private double totalconsume_ ;
      /**
       * <pre>
       * 消费合计
       * </pre>
       *
       * <code>double totalconsume = 7;</code>
       * @return The totalconsume.
       */
      public double getTotalconsume() {
        return totalconsume_;
      }
      /**
       * <pre>
       * 消费合计
       * </pre>
       *
       * <code>double totalconsume = 7;</code>
       * @param value The totalconsume to set.
       * @return This builder for chaining.
       */
      public Builder setTotalconsume(double value) {
        
        totalconsume_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消费合计
       * </pre>
       *
       * <code>double totalconsume = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalconsume() {
        
        totalconsume_ = 0D;
        onChanged();
        return this;
      }

      private double realprice_ ;
      /**
       * <pre>
       * 收款合计
       * </pre>
       *
       * <code>double realprice = 8;</code>
       * @return The realprice.
       */
      public double getRealprice() {
        return realprice_;
      }
      /**
       * <pre>
       * 收款合计
       * </pre>
       *
       * <code>double realprice = 8;</code>
       * @param value The realprice to set.
       * @return This builder for chaining.
       */
      public Builder setRealprice(double value) {
        
        realprice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 收款合计
       * </pre>
       *
       * <code>double realprice = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealprice() {
        
        realprice_ = 0D;
        onChanged();
        return this;
      }

      private Object pmname_ = "";
      /**
       * <pre>
       * 支付方式名称，多个逗号分割
       * </pre>
       *
       * <code>string pmname = 9;</code>
       * @return The pmname.
       */
      public String getPmname() {
        Object ref = pmname_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pmname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 支付方式名称，多个逗号分割
       * </pre>
       *
       * <code>string pmname = 9;</code>
       * @return The bytes for pmname.
       */
      public com.google.protobuf.ByteString
          getPmnameBytes() {
        Object ref = pmname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pmname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 支付方式名称，多个逗号分割
       * </pre>
       *
       * <code>string pmname = 9;</code>
       * @param value The pmname to set.
       * @return This builder for chaining.
       */
      public Builder setPmname(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pmname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 支付方式名称，多个逗号分割
       * </pre>
       *
       * <code>string pmname = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPmname() {
        
        pmname_ = getDefaultInstance().getPmname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 支付方式名称，多个逗号分割
       * </pre>
       *
       * <code>string pmname = 9;</code>
       * @param value The bytes for pmname to set.
       * @return This builder for chaining.
       */
      public Builder setPmnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pmname_ = value;
        onChanged();
        return this;
      }

      private Object paytime_ = "";
      /**
       * <pre>
       * 结账时间
       * </pre>
       *
       * <code>string paytime = 10;</code>
       * @return The paytime.
       */
      public String getPaytime() {
        Object ref = paytime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          paytime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 结账时间
       * </pre>
       *
       * <code>string paytime = 10;</code>
       * @return The bytes for paytime.
       */
      public com.google.protobuf.ByteString
          getPaytimeBytes() {
        Object ref = paytime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          paytime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 结账时间
       * </pre>
       *
       * <code>string paytime = 10;</code>
       * @param value The paytime to set.
       * @return This builder for chaining.
       */
      public Builder setPaytime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        paytime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 结账时间
       * </pre>
       *
       * <code>string paytime = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaytime() {
        
        paytime_ = getDefaultInstance().getPaytime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 结账时间
       * </pre>
       *
       * <code>string paytime = 10;</code>
       * @param value The bytes for paytime to set.
       * @return This builder for chaining.
       */
      public Builder setPaytimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        paytime_ = value;
        onChanged();
        return this;
      }

      private int billstatus_ ;
      /**
       * <pre>
       * 订单状态：1.有效 2.无效 3 未结
       * </pre>
       *
       * <code>int32 billstatus = 11;</code>
       * @return The billstatus.
       */
      public int getBillstatus() {
        return billstatus_;
      }
      /**
       * <pre>
       * 订单状态：1.有效 2.无效 3 未结
       * </pre>
       *
       * <code>int32 billstatus = 11;</code>
       * @param value The billstatus to set.
       * @return This builder for chaining.
       */
      public Builder setBillstatus(int value) {
        
        billstatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 订单状态：1.有效 2.无效 3 未结
       * </pre>
       *
       * <code>int32 billstatus = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBillstatus() {
        
        billstatus_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReportPosBill)
    }

    // @@protoc_insertion_point(class_scope:ReportPosBill)
    private static final ReportPosBill DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReportPosBill();
    }

    public static ReportPosBill getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportPosBill>
        PARSER = new com.google.protobuf.AbstractParser<ReportPosBill>() {
      @Override
      public ReportPosBill parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportPosBill(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportPosBill> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReportPosBill> getParserForType() {
      return PARSER;
    }

    @Override
    public ReportPosBill getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportPosBill_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportPosBill_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ReportPosBill.proto\"\323\001\n\rReportPosBill\022" +
      "\r\n\005ognid\030\001 \001(\005\022\016\n\006billid\030\002 \001(\t\022\016\n\006billno" +
      "\030\003 \001(\t\022\024\n\014businesstype\030\004 \001(\005\022\016\n\006source\030\005" +
      " \001(\005\022\017\n\007tableno\030\006 \001(\t\022\024\n\014totalconsume\030\007 " +
      "\001(\001\022\021\n\trealprice\030\010 \001(\001\022\016\n\006pmname\030\t \001(\t\022\017" +
      "\n\007paytime\030\n \001(\t\022\022\n\nbillstatus\030\013 \001(\005B#\n\016s" +
      "pace.whm.openB\021ReportPosBillInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReportPosBill_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReportPosBill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportPosBill_descriptor,
        new String[] { "Ognid", "Billid", "Billno", "Businesstype", "Source", "Tableno", "Totalconsume", "Realprice", "Pmname", "Paytime", "Billstatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
